version: 2

updates:
  - package-ecosystem: npm
    directory: "cli/"
    schedule:
      interval: daily
    versioning-strategy: increase
    ignore:
      - dependency-name: "@jakejarvis/eslint-config"
      - dependency-name: "@types/*"
    open-pull-requests-limit: 99
    labels:
      - "dependencies"
      - "cli"
