name: 'CLI: Release'

on:
  release:
    types:
      - published

jobs:
  npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
        working-directory: ./cli
      - run: yarn publish
        working-directory: ./cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  gpr:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          scope: '@jakejarvis'
      - run: yarn install --frozen-lockfile
        working-directory: ./cli
      - run: yarn publish
        working-directory: ./cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
