name: 'CLI: Tests'

on:
  push:
    branches:
    - main
    paths:
    - 'cli/**'
  pull_request:
    branches:
    - main
    paths:
    - 'cli/**'

jobs:
  test:
    strategy:
      matrix:
        node: [16.x, 14.x, 12.x]
      fail-fast: false
    runs-on: ubuntu-latest
    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - run: |
        yarn install --frozen-lockfile
        yarn lint
        yarn build
      working-directory: ./cli
